Added reactotron
loopstudio/react-hybrid pull request #8
Opened 2020-11-30 20:29 UTC by nazabalm

2020-11-30 20:39 UTC, seedwalk commented
You added `.js` files, those shouldn't be `.ts` instead?

2020-11-30 20:40 UTC, seedwalk requested changes
You added all `.js` files. Shouldn't those be `.ts`?

2020-11-30 20:41 UTC, seedwalk commented on store.js
> +/*
could we put this file inside `src/store` folder?

so it can be used from web app as well?

2020-11-30 20:42 UTC, seedwalk commented on ReactotronConfig.js
> +import Reactotron from 'reactotron-react-native';
maybe putting this one inside `src/store`

2020-11-30 20:55 UTC, seedwalk approved these changes

2020-12-02 13:20 UTC, naniverdier approved these changes

2020-12-02 13:21 UTC, merged